on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for Staging
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          role-duration-seconds: 1200
          role-session-name: StagingDeploymentSession

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Format
        working-directory: infra
        run: terraform fmt

      - name: Terraform Init
        run: |
          export $(grep -v '^#' .env.staging | xargs -0)
          cd infra
          terraform workspace list
          terraform workspace select staging || terraform workspace new staging
          terraform init -reconfigure -backend-config="bucket=aws-microservice-uploader-$ENV"
        
      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        run: |
          export $(grep -v '^#' .env.staging | xargs -0)
          cd infra
          terraform workspace list
          terraform workspace select staging || terraform workspace new staging
          terraform plan

      - name: Terraform Apply
        run: |
          export $(grep -v '^#' .env.staging | xargs -0)
          cd infra
          terraform workspace list
          terraform workspace select staging || terraform workspace new staging
          terraform apply -auto-approve

